#!/usr/bin/env bash
B=`basename $1 .smt2`
R=`./cvc5def $1`
if [ "$R" = "unsat" ]; then
    echo $1 "unsat(DEF)"
    echo $1 "unsat(DEF)" >$B.p5res
else
    R=`./cvc5fmfei $1`
    if [ "$R" = "unsat" ]; then
        echo $1 "unsat(FMFEI)"
        echo $1 "unsat(FMFEI)" >$B.p5res
    else
        R=`./cvc5di $1`
        if [ "$R" = "unsat" ]; then
            echo $1 "unsat(DI)"
            echo $1 "unsat(DI)" >$B.p5res
        else
            R=`./cvc5mqo $1`
            if [ "$R" = "unsat" ]; then
                echo $1 "unsat(MQO)"
                echo $1 "unsat(MQO)" >$B.p5res
            else
                R=`./cvc5bvi $1`
                if [ "$R" = "unsat" ]; then
                    echo $1 "unsat(BVI)"
                    echo $1 "unsat(BVI)" >$B.p5res
                else
                    echo $1 "timeout(ALL)"
                    echo $1 "timeout(ALL)" >$B.p5res
                fi
            fi
        fi
    fi
fi
